name: CI/CD Spring Boot

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: salih585/demo-github
  CONTAINER_NAME: demo-github-app
  APP_PORT: "8080"

jobs:

  # =========================
  # 1. TEST
  # =========================
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Run tests
        run: mvn clean test -B

  # =========================
  # 2. BUILD & PUSH DOCKER
  # =========================
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  # =========================
  # 3. DEPLOYMENT
  # =========================
  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Deploy container
        run: |
          echo "Deploiement sur self-hosted runner"
          docker stop demo-github-app || true
          docker rm demo-github-app || true
          docker pull salih585/demo-github:latest
          docker run -d \
            --name demo-github-app \
            -p 8080:8080 \
            --restart unless-stopped \
            salih585/demo-github:latest
          docker image prune -f
          echo "Deploiement termine avec succes"
